<a href="https://colab.research.google.com/github/maha022000/MAHALAKSHMI/blob/Data-science--projects/Linear_Regression_using_data_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Problem Statement: Linear Regression
Load the housing_price.csv dataset to a DataFrame and perform the following
tasks:
The dataset contains only numeric data, and the median house value column is
our target variable, so with the help of linear regression, build a model that can
predict accurate house prices. Perform the below tasks and build a model:
1. Load the housing_price dataset into DataFrame

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.linear_model import ElasticNet
import statsmodels.api as sm



1. Load the housing_price dataset into DataFrame

In [ ]:
df=pd.read_csv("housing_price.csv")
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                  15         5612            1283   
1    -114.47     34.40                  19         7650            1901   
2    -114.56     33.69                  17          720             174   
3    -114.57     33.64                  14         1501             337   
4    -114.57     33.57                  20         1454             326   

   population  households  median_income  median_house_value  
0        1015         472         1.4936               66900  
1        1129         463         1.8200               80100  
2         333         117         1.6509               85700  
3         515         226         3.1917               73400  
4         624         262         1.9250               65500

2. Find the null value and drop then, If any

In [ ]:
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

3. Split data into two DataFrames x and y based on dependent and
independent variables

In [ ]:
x = df.drop(columns = "median_house_value").values
y = df.median_house_value.values

In [ ]:
print("\n independent data \n" ,x)
print("\n dependent data \n",y)


 independent data 
 [[-114.31     34.19     15.     ... 1015.      472.        1.4936]
 [-114.47     34.4      19.     ... 1129.      463.        1.82  ]
 [-114.56     33.69     17.     ...  333.      117.        1.6509]
 ...
 [-124.3      41.84     17.     ... 1244.      456.        3.0313]
 [-124.3      41.8      19.     ... 1298.      478.        1.9797]
 [-124.35     40.54     52.     ...  806.      270.        3.0147]]

 dependent data 
 [ 66900  80100  85700 ... 103600  85800  94600]


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  int64  
 3   total_rooms         17000 non-null  int64  
 4   total_bedrooms      17000 non-null  int64  
 5   population          17000 non-null  int64  
 6   households          17000 non-null  int64  
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  int64  
dtypes: float64(3), int64(6)
memory usage: 1.2 MB


In [ ]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

4. Split x and y into 80% training set and 20% testing set. Set the random
state to 10. Call the LinearRegression model, then fit the model using
train data 

In [ ]:
#split test data nad train data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state = 10)

In [ ]:
#shape of test and train data (x,y)
print("x_train and x_test datset shape",x_train.shape,x_test.shape)
print("y_train and y_test datset shape",y_train.shape,y_test.shape)

x_train and x_test datset shape (13600, 8) (3400, 8)
y_train and y_test datset shape (13600,) (3400,)


4.. Call the LinearRegression model, then fit the model using
train data 

In [ ]:
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

5. Print the R2 value, coefficient, and intercept


In [ ]:
regressor.score(x_test,y_test)

0.6484403017760421

In [ ]:
#print coefficient and intercept
print("R2 value:",regressor.score(x_test,y_test))
print("\ncoefficient: \n ",regressor.coef_)
print("\nintercept:",regressor.intercept_)

R2 value: 0.6484403017760421

coefficient: 
  [-4.34225673e+04 -4.34584915e+04  1.15417922e+03 -8.34683693e+00
  1.14234465e+02 -3.87425498e+01  5.04252279e+01  4.02554220e+04]

intercept: -3635200.010897606


6. Compare actual and predicted values

In [ ]:
# find actual vs prediction
y_pred = regressor.predict(x_test)

In [ ]:
pred = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df1 = pred.head(10)
df1

Actual      Predicted
0   96100   -8475.675202
1  500001  490876.394233
2  177200  112662.107990
3   55000  218093.753334
4  220800  207600.925885
5  158300  121540.170888
6   37900  180602.126583
7  115600  104694.108104
8  359700  310765.123759
9  203300  265864.990208

7. Print the final summary

In [ ]:
# summarize the fit of the model
mse = np.mean((df1.Predicted-df1.Actual)**2)
print( "coefficient :",regressor.coef_)
print("\n intercepter :",regressor.intercept_)
print("\n mse :",mse)
print("\n final score",regressor.score(x_test,y_test))

coefficient : [-4.34225673e+04 -4.34584915e+04  1.15417922e+03 -8.34683693e+00
  1.14234465e+02 -3.87425498e+01  5.04252279e+01  4.02554220e+04]

 intercepter : -3635200.010897606

 mse : 7010137827.159782

 final score 0.6484403017760421


print the final summary using OLS MODEL

In [ ]:
X2 = sm.add_constant(x)
est = sm.OLS(y, X2)
est2 = est.fit()
print(est2.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.641
Model:                            OLS   Adj. R-squared:                  0.641
Method:                 Least Squares   F-statistic:                     3798.
Date:                Thu, 09 Mar 2023   Prob (F-statistic):               0.00
Time:                        06:34:53   Log-Likelihood:            -2.1365e+05
No. Observations:               17000   AIC:                         4.273e+05
Df Residuals:                   16991   BIC:                         4.274e+05
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.621e+06   6.92e+04    -52.312      0.0