<a href="https://colab.research.google.com/github/maha022000/MAHALAKSHMI/blob/Data-science--projects/Numpy_array_using_stacks_and_swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Define a NumPy array with 4*5 dimensions, and swap the array's dimensions to
make it 5*4 using suitable functions.


In [ ]:
import numpy as np
x=np.arange(20)
print("Original array is:")
print(x)
y=np.reshape(x,(4,5))
print("Reshaped array is:")
print(y)
z=y.T
print("Transpose of array :")
print(z)


Original array is:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped array is:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Transpose of array :
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


Write a Python program to create two 2-dimensional arrays and apply
hstack(), vstack(), concatenate(), and split() functions to
them to get the output as shown below

In [ ]:
import numpy as np
a=np.arange(1,5).reshape(2,2)
print("The first array is")
print(a)
b=np.arange(6,10).reshape(2,2)
print("The second array is")
print(b)
c=np.stack((a,b))
print("Applying hstack() function:")
print(c)
d=np.vstack((a,b))
print("applying vsatck() function:")
print(d)
e=np.concatenate((a,b),axis=0)
print("Applying concatenate() fuction:")
print(e)
f=np.split(c,2)
print("applying split() fuction:")
print(f)




The first array is
[[1 2]
 [3 4]]
The second array is
[[6 7]
 [8 9]]
Applying hstack() function:
[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]
applying vsatck() function:
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
Applying concatenate() fuction:
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
applying split() fuction:
[array([[[1, 2],
        [3, 4]]]), array([[[6, 7],
        [8, 9]]])]
